### ISSUE TITLE
Pictures missing inside movies

### ISSUE THREAD

**Issue by wayneward** [dslul/cinema-scope#9]
Since update to ota 11 when you enter a movie the images have a cross through them, tested bq E5 and bq m10 tablet

**Comment by dslul** [comment]
Thank you for reporting, can you please provide me a picture of the problem?

**Comment by wayneward** [comment]
Thankyou for your reply
Does thia on both out bqe5 and the m10 aswell

Wayne 

n Sunday, 3 July 2016 07:11:51 BST, Daniele Laudani 
<notifications@github.com> wrote:
> Thank you for reporting, can you please provide me a picture of 
> the problem?
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dslul/cinema-scope/issues/9#issuecomment-230137658


-- 
Sent using Dekko from my Ubuntu device

**Comment by wayneward** [comment]
did photos come through ok

Wayne :)

n Sat, 2016-07-02 at 23:11 -0700, Daniele Laudani wrote:

**Comment by dslul** [comment]
No, i cannot see any photo...did you upload them here?

**Comment by wayneward** [comment]
![screenshot20160703_103824346](https://cloud.githubusercontent.com/assets/11428255/16563392/b6a879cc-41f9-11e6-95b5-9d9a74ab5a1e.png)
![screenshot20160703_103839777](https://cloud.githubusercontent.com/assets/11428255/16563393/b6b25226-41f9-11e6-90ae-5db641a6c169.png)

**Comment by mateosalta** [comment]
it is really strange - in actors it even shows a missing movie at the top of the actor.

also in some of my scopes it is showing a picture in the details that I specifically didn't show in certain layouts, I think somehow it is overriding and showing all elements listed at some point - because the elements that are "missing" seem to be code for the actor's face or other such items - also this is happening on the latest update as well. Don't know, but it seems to be making a placeholder for all elements, even if they don't have an item - maybe pushing the sections needs to be separated? not sure, something changed on the os side on how it displays these items though.

**Comment by dslul** [comment]
Fixed in https://github.com/dslul/cinema-scope/commit/14112b177c3f0ca236942728854b5108ac2d8c6c

**Comment by wayneward** [comment]
im on proposed 
will this update come into action soon
i still have a cross through images when select a movie.

Wayne


On Tuesday, 8 November 2016 10:17:15 GMT, Daniele Laudani 

<notifications@github.com> wrote:
> Fixed in 
> https://github.com/dslul/cinema-scope/commit/14112b177c3f0ca236942728854b5108ac2d8c6c
> 



-- 
Sent using Dekko from my Ubuntu device

**Comment by wayneward** [comment]
im on proposed and still have the cross through picture when select movie
when will the update for the fix be expected :)

Wayne

On Tuesday, 8 November 2016 10:17:15 GMT, Daniele Laudani 
<notifications@github.com> wrote:
> Fixed in 
> https://github.com/dslul/cinema-scope/commit/14112b177c3f0ca236942728854b5108ac2d8c6c
> 



-- 
Sent using Dekko from my Ubuntu device

**Comment by dslul** [comment]
Sorry, I forgot to publish it, you should see it right away :)
